project: boot
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  banner:
    charset: UTF-8
  mvc:
    view:
      prefix: /static/
    static-path-pattern: /static/**

server:
  port: 8088
  servlet:
    context-path: /${project}
  tomcat:
    uri-encoding: utf-8